/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:6d194473-7d01-46bd-936d-a4faa8e1f3ce",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_yU1OJtC6x",
    "aws_user_pools_web_client_id": "rml25fubferven7bna5e0f4u0",
    "oauth": {}
};


export default awsmobile;
