/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:6d194473-7d01-46bd-936d-a4faa8e1f3ce",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_yU1OJtC6x",
    "aws_user_pools_web_client_id": "rml25fubferven7bna5e0f4u0",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://zllwv4tw4jbipczvdy2uyt37lq.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-nl2r5gikfrbmjapw67vvrefj7i",
    "aws_user_files_s3_bucket": "amplifybucket205832-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
